@echo off
echo Starting EngageResolve Development Stack...
echo 1. Seeding Backend Database and Starting Flask Server...
start cmd /k "cd backend && set PYTHONPATH=. && python run.py --seed"
echo 2. Starting Expo Frontend Web Server...
start cmd /k "cd frontend && npm run web"
echo Dev stack started! Flask API: http://localhost:5000 | Frontend: http://localhost:8081
